name = "DihedralParametrization"
uuid = "750fe09c-d507-4c3d-8cfa-192ca0812517"
version = "1.0.0-DEV"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]

[deps]
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8"
BioStructures = "4.7"
DifferentiationInterface = "0.7.7"
ExplicitImports = "1.15"
FiniteDifferences = "0.12.33"
ForwardDiff = "1"
LinearAlgebra = "1.0"
Mooncake = "0.4.159"
Random = "1.0"
StaticArrays = "1.9"
Test = "1.0"
julia = "1.10.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "DifferentiationInterface", "ExplicitImports", "FiniteDifferences", "ForwardDiff", "Mooncake", "Random", "Test"]
